# Generated by Django 5.0.3 on 2024-06-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parking Place Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, verbose_name='Condition of the Parking Place')),
                ('photo1', models.ImageField(upload_to='parking_place_photos', verbose_name='Photo 1')),
                ('photo2', models.ImageField(upload_to='parking_place_photos', verbose_name='Photo 2')),
                ('photo3', models.ImageField(upload_to='parking_place_photos', verbose_name='Photo 3')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parkingplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
