# Generated by Django 5.0.3 on 2024-06-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_parkingplace_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
